name = "HashCode2014Sol"
uuid = "a17671bd-a8df-47c0-9b5c-ccc7205f4d81"
authors = ["Karen Chung <karenchung117@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HashCode2014 = "7bbed249-721d-42ac-b1f6-7cf884be0fbe"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
